# Generated by Django 4.2.7 on 2023-11-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dep_name',
            new_name='dep_dep',
        ),
    ]
