# Generated by Django 4.2.7 on 2023-11-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_booking_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors'),
        ),
    ]
